### ISSUE TITLE
Module not listed on https://docs.laminas.dev/mvc/

### ISSUE THREAD

**Issue by michalbundyra** [laminas/laminas-mvc-middleware#1]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | master

#### Summary

The module is MVC integration module and it should be listed on:
https://docs.laminas.dev/mvc/

Currently is not.

I know it has not been yet released so maybe it can be postpone until release.

**Comment by froschdesign** [comment]
@michalbundyra 
Good catch!

Until now there is no release for this module and therefore we should add a notice on the entry page.

**Comment by froschdesign** [comment]
Fixed with https://github.com/laminas/laminas.github.io/pull/78
