### ISSUE TITLE
Parameters from RouteMatch are not passed to PSR-7 request

### ISSUE THREAD

**Issue by boesing** [laminas/laminas-mvc-middleware#14]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 2.0.0

#### Summary

The parameters from the route match are not passed to the PSR-7 `ServerRequestInterface`.
Only the `RouteMatch` itself is passed to the request but the route match is a detail I mostly dont care about when working with the Middleware pattern.

Not sure if thats a thing only for mezzio, but `mezzio-router` passes all arguments from the matched route as attributes aswell.  If thats mezzio-only, this "Bug Report" can be changed to a "Feature Request" instead.

#### Current behavior

When using `$request->getAttribute('parameter');`, I am not able to receive the `Segment`-Route path parameter (for example).

#### How to reproduce

```php
use Laminas\Mvc\Middleware\PipeSpec;

return [
    'routes' => [
        'foo' => [
            'type' => 'segment',
            'options' => [
                'route' => '/foo/:parameter',
                'defaults' => [
                    'controller' => PipeSpec::class,
                    'middleware' => new PipeSpec(FooHandler::class),
                ],
            ],
        ],
    ],
];
```

```php
use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Server\RequestHandlerInterface;

final class FooHandler implements RequestHandlerInterface
{
    public function handle(ServerRequestInterface $request): ResponseInterface
    {
        $parameter = $request->getAttribute('parameter');
    }
}

```

#### Expected behavior

`$parameter` contains the parameter from the segment route match.

**Comment by boesing** [comment]
Hm, it seems that it was part in v1.x but it was removed in v2.x.

https://github.com/laminas/laminas-mvc-middleware/blob/835b3e686945f7485b6fad66689fde058492551c/src/MiddlewareController.php#L124

**Comment by Xerkus** [comment]
This was intentional change. Because request attributes are used to pass trusted context down the pipe it is unsafe to inject route match parameters directly as attributes.

**Comment by boesing** [comment]
Just to recap - do you say, using `mezzio-router` is unsafe?

**Comment by froschdesign** [comment]
@boesing 
Fetch the route match:

```php
/** @var Laminas\Router\RouteMatch $routeMatch */
$routeMatch = $request->getAttribute(Laminas\Router\RouteMatch::class);
var_dump($routeMatch->getParams());
var_dump($routeMatch->getParam('parameter'));
```

```
array (size=3)
  'controller' => string 'Laminas\Mvc\Middleware\PipeSpec' (length=31)
  'middleware' => string 'Application\Handler\MyHandler' (length=34)
  'parameter' => string 'example' (length=7)

string 'example' (length=7)
```

**Comment by Xerkus** [comment]
If it injects each route match param as attribute then yes, potentially unsafe.

**Comment by boesing** [comment]
@froschdesign I know there is a workaround, but thats **AGAIN** a difference to how mezzio works and thus, this package is not usable for me.

Thanks for the insights. As this package does not suit my needs, I'll probably creating a fork of this which synchronizes with `mezzio-router`.

In a company, where you work with `mezzio` and `laminas-mvc` and where developers work on different levels, it is a nightmare to remember different styles of writing code just to have the middleware pattern up and ready to use. In the Laminas project (no matter if mezzio or not) I would prefer having the same styles. 
We are applying laminas coding style in every package, having the same continous integration logic, have standards on how to create documentations but when it comes to implementations, every component makes its own decisions. 
I'd prefer having more synchronicity between laminas projects. This is not symfony-style vs laminas-style. This makes me sad.

@Xerkus maybe we should add a RFC for that on `mezzio-router` to inform all users that their projects are potentially unsafe?

**Comment by froschdesign** [comment]
> @froschdesign I know there is a workaround…

I assumed you knew it, but the info was missing in your initial post.

> …but thats **AGAIN** a difference to how mezzio works…

Right, the next unnecessary difference. 😞

**Comment by Xerkus** [comment]
> @Xerkus maybe we should add a RFC for that on `mezzio-router` to inform all users that their projects are potentially unsafe?

I would say RFC to consider whether that behavior should be dropped. At the very least I would want to move it out into an opt-in middleware.
