### ISSUE TITLE
Doesn't work with composer 2

### ISSUE THREAD

**Issue by snapshotpl** [laminas/laminas-mvc-middleware#8]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 1.1.0

After `composer update` using composer 2:

```
  Problem 1
    - webimpress/composer-extra-dependency 0.2.2 requires composer-plugin-api ^1.1 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
    - laminas/laminas-stratigility 2.2.2p2 requires webimpress/http-middleware-compatibility ^0.1.4 -> satisfiable by webimpress/http-middleware-compatibility[0.1.4].
    - laminas/laminas-mvc-middleware 1.1.0 requires laminas/laminas-stratigility ^2.2.2p2 -> satisfiable by laminas/laminas-stratigility[2.2.2p2].
    - webimpress/http-middleware-compatibility 0.1.4 requires webimpress/composer-extra-dependency ^0.2.2 -> satisfiable by webimpress/composer-extra-dependency[0.2.2].
    - Root composer.json requires laminas/laminas-mvc-middleware ^1.1 -> satisfiable by laminas/laminas-mvc-middleware[1.1.0].

```

**Comment by weierophinney** [comment]
Can you issue a `composer why webimpress/composer-extra-dependency` and report the results, please?

It's clear you're on Composer v2, but I need to see why that particular dependency is being brought in.

**Comment by weierophinney** [comment]
Looks like the tree is something like this:

```text
- laminas/laminas-stratigility 2.2.2p2
  - webimpress/http-middleware-compatibility 0.1.4
    - webimpress/composer-extra-dependency 0.2.2
```

As such, you'll need to report it upstream; we can't fix it here until then.

**Comment by snapshotpl** [comment]
Or we can move forward with #3

**Comment by rieschl** [comment]
> Looks like the tree is something like this:
> 
> ```
> - laminas/laminas-stratigility 2.2.2p2
>   - webimpress/http-middleware-compatibility 0.1.4
>     - webimpress/composer-extra-dependency 0.2.2
> ```
> 
> As such, you'll need to report it upstream; we can't fix it here until then.

yes, it's really stratigility 2.2 (and 2.1) that's requiring the incompatible package, not this one. and 2.x is EOL, right? so 🤷‍♂️

**Comment by Xerkus** [comment]
Won't be fixed for 1.x, should be gone for 2.0
